name: Deploy Lambda Function
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: default deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws_region: ${{ secrets.AWS_REGION }}
          aws-region: eu-west-3
          function-name: CopyFileToCurratedDataSetCompagnie
          source: CopyFileToCurratedDataSetCompagnie/lambda_function.py 